artifact_uri: /mlflow/716023700256294932/f04d06b033034a7cbb9d36ba58e7fbf9/artifacts
end_time: 1757500249940
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: f04d06b033034a7cbb9d36ba58e7fbf9
run_name: method-mini-lr-0.01-reg-Normal-poly-False-momentum-False-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757500032687
status: 3
tags: []
user_id: Nabin
