artifact_uri: /mlflow/868384881951641329/68d8f5b1420d491a88acdfad5a1222ef/artifacts
end_time: 1757513259169
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 68d8f5b1420d491a88acdfad5a1222ef
run_name: method-sto-lr-0.001-reg-Ridge-poly-False-momentum-Momentum Used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757512901099
status: 3
tags: []
user_id: Nabin
