artifact_uri: /mlflow/868384881951641329/bad0d5d8d60147e1aca76bbc5ea343ce/artifacts
end_time: 1757510416787
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: bad0d5d8d60147e1aca76bbc5ea343ce
run_name: method-sto-lr-0.01-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757510017817
status: 3
tags: []
user_id: Nabin
