artifact_uri: /mlflow/868384881951641329/2fae0ecf42664accbf4db8d2c1c4cacb/artifacts
end_time: 1757523842519
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 2fae0ecf42664accbf4db8d2c1c4cacb
run_name: Fold-2
source_name: ''
source_type: 4
source_version: ''
start_time: 1757523596085
status: 3
tags: []
user_id: Nabin
