version: "3.9"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: machinelearningcar2:latest
    ports:
      - "8888:8888" # Jupyter Notebook host port
    volumes:
      - ./code:/root/code
    environment:
      - JUPYTER_PASSWORD_HASH=argon2:$argon2id$v=19$m=10240,t=10,p=8$btpQFdm0YERLMLZl1iyFnQ$DlptzSUOs7ut+59YPk84ydjk2EbCOLewBRR12hTOrp4
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888
      --NotebookApp.password=$JUPYTER_PASSWORD_HASH
      --NotebookApp.token=''
      --notebook-dir=/root/code
      --no-browser
      --allow-root

  dash:
    build:
      context: .
      dockerfile: Dockerfile
    image: nabin-dash-car:latest
    ports:
      - "8050:80" # Dash host port
    volumes:
      - ./code:/root/code
    command: python3 /root/code/app.py

  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    image: mlflow-car:latest
    ports:
      - "5001:5000" # MLflow host port
    volumes:
      - ./_mlflow:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlflow/mlruns
      --default-artifact-root /mlflow/mlruns
