artifact_uri: /mlflow/868384881951641329/6b5b5bad24a64ca89ee72721eac09cd7/artifacts
end_time: 1757517840530
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 6b5b5bad24a64ca89ee72721eac09cd7
run_name: method-mini-lr-0.01-reg-Ridge-poly-False-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757517616615
status: 3
tags: []
user_id: Nabin
