digest: '36281226'
name: dataset
profile: '{"features_shape": [2140, 34], "features_size": 72760, "features_nbytes":
  582080, "targets_shape": [2140], "targets_size": 2140, "targets_nbytes": 17120}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 34]}}]", "targets": "[{\"type\": \"tensor\",
  \"tensor-spec\": {\"dtype\": \"float64\", \"shape\": [-1]}}]"}}'
source: '{"tags": {"mlflow.user": "Nabin", "mlflow.source.name": "/usr/local/lib/python3.10/site-packages/ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
