artifact_uri: /mlflow/716023700256294932/e646ac5bb8824efdb1b71beb2a9b3984/artifacts
end_time: 1757500596296
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: e646ac5bb8824efdb1b71beb2a9b3984
run_name: method-mini-lr-0.001-reg-Normal-poly-False-momentum-False-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757500250004
status: 3
tags: []
user_id: Nabin
