artifact_uri: /mlflow/868384881951641329/02a650ffafd14ab5b2e2acd6da04c67d/artifacts
end_time: 1757520000505
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 02a650ffafd14ab5b2e2acd6da04c67d
run_name: method-mini-lr-0.001-reg-Ridge-poly-True-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757519679999
status: 3
tags: []
user_id: Nabin
