artifact_uri: /mlflow/716023700256294932/7d77efbd4b6b4b77953ff07f4aace831/artifacts
end_time: 1757505452500
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: 7d77efbd4b6b4b77953ff07f4aace831
run_name: method-sto-lr-0.0001-reg-Ridge-poly-True-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757505015486
status: 3
tags: []
user_id: Nabin
