artifact_uri: /mlflow/716023700256294932/a7b2df60172d4ff2ac15aa823d087fdc/artifacts
end_time: 1757492021683
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: a7b2df60172d4ff2ac15aa823d087fdc
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757491997640
status: 3
tags: []
user_id: Nabin
