artifact_uri: /mlflow/868384881951641329/110bfab8ed224ec68abe1989f6b05f1f/artifacts
end_time: 1757518884938
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 110bfab8ed224ec68abe1989f6b05f1f
run_name: method-mini-lr-0.0001-reg-Ridge-poly-False-momentum-Momentum Used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757518584444
status: 3
tags: []
user_id: Nabin
