artifact_uri: /mlflow/716023700256294932/75fe76faf86f447f9e4871e3fdba8e30/artifacts
end_time: 1757506022289
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: 75fe76faf86f447f9e4871e3fdba8e30
run_name: method-sto-lr-0.01-reg-Ridge-poly-False-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757505452587
status: 3
tags: []
user_id: Nabin
