artifact_uri: /mlflow/868384881951641329/0663bd7167a343d2ba58fbfd42abc9ec/artifacts
end_time: 1757510910656
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 0663bd7167a343d2ba58fbfd42abc9ec
run_name: method-sto-lr-0.0001-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757510708835
status: 3
tags: []
user_id: Nabin
