artifact_uri: /mlflow/868384881951641329/767d1ee025c74a3fbe4a0e73b898cdc8/artifacts
end_time: 1757524837785
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 767d1ee025c74a3fbe4a0e73b898cdc8
run_name: method-batch-lr-0.001-reg-Ridge-poly-False-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757524342593
status: 3
tags: []
user_id: Nabin
