artifact_uri: /mlflow/868384881951641329/431dbfcf296a4d80ab6748b61ab344b4/artifacts
end_time: 1757522672050
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 431dbfcf296a4d80ab6748b61ab344b4
run_name: method-batch-lr-0.01-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757522184807
status: 3
tags: []
user_id: Nabin
