artifact_uri: /mlflow/716023700256294932/7111ad2f75604fde9b0debafcabf9240/artifacts
end_time: 1757493800303
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: 7111ad2f75604fde9b0debafcabf9240
run_name: method-sto-lr-0.0001-reg-Ridge-poly-True-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757493382679
status: 3
tags: []
user_id: Nabin
