artifact_uri: /mlflow/716023700256294932/3f396d6c7422467ebcacbe0428f7fdc9/artifacts
end_time: 1757501635891
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: 3f396d6c7422467ebcacbe0428f7fdc9
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757501621197
status: 3
tags: []
user_id: Nabin
