digest: 96556d4b
name: dataset
profile: '{"features_shape": [32, 102], "features_size": 3264, "features_nbytes":
  26112, "targets_shape": [32], "targets_size": 32, "targets_nbytes": 256}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 102]}}]", "targets": "[{\"type\": \"tensor\",
  \"tensor-spec\": {\"dtype\": \"float64\", \"shape\": [-1]}}]"}}'
source: '{"tags": {"mlflow.user": "Nabin", "mlflow.source.name": "/usr/local/lib/python3.10/site-packages/ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
