artifact_uri: /mlflow/716023700256294932/7ee8b66a6cc14d879ea6e19b5812ac56/artifacts
end_time: 1757503835456
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: 7ee8b66a6cc14d879ea6e19b5812ac56
run_name: method-sto-lr-0.01-reg-Ridge-poly-True-momentum-Momentum Used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757503322992
status: 3
tags: []
user_id: Nabin
