artifact_uri: /mlflow/716023700256294932/e295d46e460e476589fe3bdb8c34ce91/artifacts
end_time: null
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: e295d46e460e476589fe3bdb8c34ce91
run_name: method-sto-lr-0.01-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757507372132
status: 1
tags: []
user_id: Nabin
