artifact_uri: /mlflow/868384881951641329/54ea83aeb2fe4e0dae5a7578002f305f/artifacts
end_time: 1757510708776
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 54ea83aeb2fe4e0dae5a7578002f305f
run_name: method-sto-lr-0.001-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757510416844
status: 3
tags: []
user_id: Nabin
