artifact_uri: /mlflow/868384881951641329/e5160911750e48bfacb4a668cae6ac1d/artifacts
end_time: 1757511294384
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: e5160911750e48bfacb4a668cae6ac1d
run_name: method-sto-lr-0.01-reg-Ridge-poly-False-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757510910722
status: 3
tags: []
user_id: Nabin
