artifact_uri: /mlflow/868384881951641329/e459da4cf78b42f7bf3b5da83b9ccb6b/artifacts
end_time: 1757515981492
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: e459da4cf78b42f7bf3b5da83b9ccb6b
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum Used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757515974053
status: 3
tags: []
user_id: Nabin
