artifact_uri: /mlflow/868384881951641329/487366d5cb6b4b9daab89b4e99f6a017/artifacts
end_time: 1757516921755
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 487366d5cb6b4b9daab89b4e99f6a017
run_name: method-mini-lr-0.0001-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757516605609
status: 3
tags: []
user_id: Nabin
