artifact_uri: /mlflow/868384881951641329/bdc9c01a9d8a412aa7b1430ff16e7815/artifacts
end_time: 1757512457235
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: bdc9c01a9d8a412aa7b1430ff16e7815
run_name: method-sto-lr-0.001-reg-Ridge-poly-False-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757512189260
status: 3
tags: []
user_id: Nabin
