artifact_uri: /mlflow/868384881951641329/c7bd85c71e8249f89d1cebc20606e6b8/artifacts
end_time: 1757513897746
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: c7bd85c71e8249f89d1cebc20606e6b8
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757513874205
status: 3
tags: []
user_id: Nabin
