artifact_uri: /mlflow/716023700256294932/e6e67f80b3cc4760b8d4dab3386aab3c/artifacts
end_time: 1757493382616
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: e6e67f80b3cc4760b8d4dab3386aab3c
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757493351497
status: 3
tags: []
user_id: Nabin
