artifact_uri: /mlflow/716023700256294932/fa4672db46dd40009a224be2db6d947d/artifacts
end_time: 1757505015386
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: fa4672db46dd40009a224be2db6d947d
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757504966674
status: 3
tags: []
user_id: Nabin
