artifact_uri: /mlflow/868384881951641329/760c52a0be60496da2f3a76cca6bb8b9/artifacts
end_time: 1757515645815
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 760c52a0be60496da2f3a76cca6bb8b9
run_name: method-sto-lr-0.0001-reg-Ridge-poly-True-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757515177740
status: 3
tags: []
user_id: Nabin
