artifact_uri: /mlflow/716023700256294932/f4f82fe8f4a445ce9cbca0435fbc19d4/artifacts
end_time: 1757502554269
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: f4f82fe8f4a445ce9cbca0435fbc19d4
run_name: method-sto-lr-0.01-reg-Ridge-poly-True-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757502060229
status: 3
tags: []
user_id: Nabin
