artifact_uri: /mlflow/868384881951641329/3810cac44c9f42fc9826b8f47c0fc9c7/artifacts
end_time: 1757518243026
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 3810cac44c9f42fc9826b8f47c0fc9c7
run_name: method-mini-lr-0.0001-reg-Ridge-poly-False-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757517950461
status: 3
tags: []
user_id: Nabin
