artifact_uri: /mlflow/868384881951641329/01f9e8bb73a1409dbd161c3d8ca51daf/artifacts
end_time: 1757518584383
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 01f9e8bb73a1409dbd161c3d8ca51daf
run_name: method-mini-lr-0.001-reg-Ridge-poly-False-momentum-Momentum Used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757518500877
status: 3
tags: []
user_id: Nabin
