artifact_uri: /mlflow/868384881951641329/f69db34afcad4867a1fcb95978fed811/artifacts
end_time: 1757514547465
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: f69db34afcad4867a1fcb95978fed811
run_name: method-sto-lr-0.01-reg-Ridge-poly-True-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757514280405
status: 3
tags: []
user_id: Nabin
