artifact_uri: /mlflow/716023700256294932/ddaff1ed24cd40b8b0867cd65cc8d2c4/artifacts
end_time: 1757503852514
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: ddaff1ed24cd40b8b0867cd65cc8d2c4
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum Used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757503835538
status: 3
tags: []
user_id: Nabin
