artifact_uri: /mlflow/868384881951641329/f5aab8738a1141efa54ab95f18a97fb1/artifacts
end_time: 1757520422989
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: f5aab8738a1141efa54ab95f18a97fb1
run_name: method-mini-lr-0.01-reg-Ridge-poly-True-momentum-Momentum not used-init-xavier
source_name: ''
source_type: 4
source_version: ''
start_time: 1757520230219
status: 3
tags: []
user_id: Nabin
