digest: ad579f1d
name: dataset
profile: '{"features_shape": [4281, 34], "features_size": 145554, "features_nbytes":
  1164432, "targets_shape": [4281], "targets_size": 4281, "targets_nbytes": 34248}'
schema: '{"mlflow_tensorspec": {"features": "[{\"type\": \"tensor\", \"tensor-spec\":
  {\"dtype\": \"float64\", \"shape\": [-1, 34]}}]", "targets": "[{\"type\": \"tensor\",
  \"tensor-spec\": {\"dtype\": \"float64\", \"shape\": [-1]}}]"}}'
source: '{"tags": {"mlflow.user": "Nabin", "mlflow.source.name": "/usr/local/lib/python3.10/site-packages/ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
