artifact_uri: /mlflow/716023700256294932/ea1c0dff6abc43e88e8f95f8d24b2021/artifacts
end_time: 1757491997577
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: ea1c0dff6abc43e88e8f95f8d24b2021
run_name: method-sto-lr-0.01-reg-Ridge-poly-True-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757491612212
status: 3
tags: []
user_id: Nabin
