artifact_uri: /mlflow/868384881951641329/cfa107e0ac5a4ad9bcc51743d7b67bfe/artifacts
end_time: 1757514760019
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: cfa107e0ac5a4ad9bcc51743d7b67bfe
run_name: method-sto-lr-0.0001-reg-Ridge-poly-True-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757514554770
status: 3
tags: []
user_id: Nabin
