artifact_uri: /mlflow/868384881951641329/d7bfe2c6bea945f1aff8ec0796e3cf1b/artifacts
end_time: 1757523878478
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: d7bfe2c6bea945f1aff8ec0796e3cf1b
run_name: method-batch-lr-0.0001-reg-Ridge-poly-False-momentum-Momentum not used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757523228494
status: 3
tags: []
user_id: Nabin
