artifact_uri: /mlflow/716023700256294932/92cffc43d8184528b3da3dad74a9dc2d/artifacts
end_time: 1757491283966
entry_point_name: ''
experiment_id: '716023700256294932'
lifecycle_stage: active
run_id: 92cffc43d8184528b3da3dad74a9dc2d
run_name: method-sto-lr-0.001-reg-Ridge-poly-True-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757491273255
status: 3
tags: []
user_id: Nabin
