artifact_uri: /mlflow/868384881951641329/629bbb52c0c44f0bb15ca2bedc173f2a/artifacts
end_time: 1757527396495
entry_point_name: ''
experiment_id: '868384881951641329'
lifecycle_stage: active
run_id: 629bbb52c0c44f0bb15ca2bedc173f2a
run_name: method-batch-lr-0.0001-reg-Ridge-poly-False-momentum-Momentum Used-init-zero
source_name: ''
source_type: 4
source_version: ''
start_time: 1757524837954
status: 3
tags: []
user_id: Nabin
